#ifndef _MULTIBOOT_H_
#define _MULTIBOOT_H_

#define MB_HEADER_MAGIC     0x1BADB002
#define MB_BOOTLOADER_MAGIC 0x2BADB002

#define MB_FLAG_ALIGN_MODULES 0x0001
#define MB_FLAG_MEMORY_INFO   0x0002

#endif // _MULTIBOOT_H_
